Update create_aks_and_deploy.yaml

diff --git a/.github/workflows/create_aks_and_deploy.yaml b/.github/workflows/create_aks_and_deploy.yaml
--- a/.github/workflows/create_aks_and_deploy.yaml
+++ b/.github/workflows/create_aks_and_deploy.yaml
@@ -133,9 +133,19 @@ jobs:
       - name: Deploy to AKS
         run: |
           echo "Deploying to AKS..."
+          echo "Deployment: ${{ secrets.DEPLOYMENT_NAME }}"
+          echo "Container: ${{ secrets.CONTAINER_NAME }}"
+          echo "Image: ${{ env.IMAGE_FULL_NAME }}"
+          if [ -z "${{ secrets.DEPLOYMENT_NAME }}" ] || [ -z "${{ secrets.CONTAINER_NAME }}" ]; then
+          echo "❌ Missing secrets DEPLOYMENT_NAME or CONTAINER_NAME. Please set them in GitHub → Settings → Secrets → Actions."
+          exit 1
+          fi
+
           kubectl set image deployment/${{ secrets.DEPLOYMENT_NAME }} \
-            ${{ secrets.CONTAINER_NAME }}=${{ env.IMAGE_FULL_NAME }}
-          kubectl rollout status deployment/${{ secrets.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
+          ${{ secrets.CONTAINER_NAME }}=${{ env.IMAGE_FULL_NAME }} \
+          -n ${{ env.NAMESPACE }}
+
+            kubectl rollout status deployment/${{ secrets.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
 
       # Step 11: Verify Deployment
       - name: Verify Deployment
